// Названия позиций меню из seed v2.1 (меню, распознанное с фото).
// Нужны только миграции 2.2: всё, чего нет в этом списке и в новом меню, —
// позиции, которые бар добавил сам через бота; их миграция сохраняет.
export const LEGACY_MENU_NAMES_21 = [
  "Картофель фри с трюфельным майо",
  "Батат фри с соусом блю чиз",
  "Чипсы с красной/чёрной икрой",
  "Тартар из говядины блю чиз",
  "Тартар из говядины",
  "Фаршированные яйца с красной икрой",
  "Креветочные шарики с соусом спайси-майо",
  "Запечённые черри со взбитой фетой",
  "Салат с осьминогом",
  "Севиче из дальневосточного гребешка",
  "Буррата с томатами",
  "Табуле",
  "Креветки / сальса / копчёная страчателла",
  "Зеленый салат",
  "Салат хориатики",
  "Крудо из бралтуца с морковным агачиле",
  "Салат с черешней",
  "Сезонные овощи с дзадзыки",
  "Коппа / персик / страчателла",
  "Вяленые томаты",
  "Оливки",
  "Артишоки",
  "Хамон",
  "Сесина",
  "Сыр манчего выдержанный",
  "Сыр манчего с трюфелем",
  "Молодой козий сыр",
  "Хлеб санчоусным маслом",
  "Перец с рататуй и тоннато",
  "Томатный суп и гриль чиз",
  "Фокачча сэндвич с прошутто котто",
  "Чикен сэндвич",
  "Хрустящий цыплёнок с ромейном",
  "Маффин с яйцом",
  "Бифштекс с перечным соусом",
  "Щупальце осьминога с соусом из чоризо",
  "Палтус с рататуй и дзадзыки",
  "Бананы фостер",
  "Сырный мусс с жжёным лимоном",
  "Яблочный пирог",
  "DIN45500",
  "ABBA",
  "MINIMOG",
  "WALKMAN",
  "FAIRLIGHT CMI",
  "ITUNES",
  "808",
  "GRAMOPHONE",
  "GIBSON −72°",
  "LONGLAY",
  "SKINNY BITCH",
  "BELLINI",
  "GIN&TONIC on a tap",
  "BLOODY MARY",
  "AMARETTO SOUR",
  "AVIATION",
  "COSMOPOLITAN",
  "TOMMY’S MARGARITA",
  "NEGRONI",
  "DRY MARTINI",
  "VIRGIN DIN45500",
  "VIRGIN BELLINI",
  "VIRGIN MICHELADA",
  "ALICE ADONIS",
  "GIN MAID 75",
  "BOULEVARDIER",
  "PENICILLIN + BLUE CHEESE TARTAR",
  "PORNSTAR MARTINI",
  "WATERMELON FROZEN MARGO",
  "COCO NEGRONI",
  "APEROL SPRITZ",
  "OYSTER MICHELADA",
  "KITOS NEGRONI",
  "IDIOT WHISKEY COLA",
  "CLASE AZUL MARGO",
  "CHAMPAGNE COCKTAIL",
  "PORNSTAR MARTINI COCKTAIL TREE",
  "DEWAR’S WHITE LABEL",
  "DEWAR’S 8 Y.O.",
  "CRAIGELLACHIE 13 Y.O.",
  "GLENFIDDICH 15 YEARS OLD",
  "ARDBEG 10 Y.O.",
  "ROYAL BRACKLA 12 Y.O.",
  "TAMDHU AGED 12 YEARS",
  "MACALLAN 12 Y.O DOUBLE CASK",
  "BUSHMILLS 10 Y.O. SINGLE MALT",
  "TEELING SMALL BATCH",
  "TEELING SINGLE MALT BLACKPITTS",
  "TEELING SINGLE MALT",
  "MAKER’S MARK",
  "ABASOLO ALMA DE LA TIERRA",
  "KEMILIYA RUSSIAN RYE",
  "KAVALAN DISTILLERY SELECT #1",
  "NOBUSHI SINGLE GRAIN",
  "HATOZAKI BLENDED",
  "LIBELAJO JOVEN",
  "MARAMEC PLATA",
  "CORRALEJO BLANCO",
  "ESPOLON ANEJO",
  "ESPOLON BLANCO",
  "ESPOLON CRISTALINO",
  "CAVA DE ORO EXTRA AÑEJO BLACK",
  "DON JULIO 1942 AÑEJO",
  "CLASE AZUL REPOSADO",
  "MONTELOBOS ESPADÍN",
  "SE BUSCA JOVEN MADRECUILHE",
  "BUEN AMIGO JOVEN",
  "RAICILLA LA VENENOSA SIERRA DEL TIGRE",
  "SOTOL NOCHELUNA",
  "CLASE AZUL DURANGO",
  "CLASE AZUL GUERRERO",
  "CLASE AZUL SAN LUIS POTOSÍ",
  "COURVOISIER VS",
  "COURVOISIER VSOP",
  "BARON OTARD VSOP",
  "FRANCOIS DE MARTIGNAC XO",
  "TIO TOTO BRANDY DE JEREZ",
  "BUSNEL FINE PAYS D’AUGE",
  "BLANCHE DE NORMANDIE",
  "PISCO VINAS DE ORO TORONTEL",
  "GOSLING’S BLACK SEAL",
  "ANGOSTURA RESERVA 3 Y.O.",
  "EL RON PROHIBIDO 12 Y.O.",
  "PLANTATION THREE STARS",
  "BACARDI OAKHEART ORIGINAL",
  "BUMBU ORIGINAL",
  "BOTUCAL MONTUANO EXTRA ANEJO",
  "ZACAPA 23 Y.O.",
  "CACHAÇA VELHO BARREIRO",
  "RHUM JM BLANC",
  "ROKU GIN",
  "SIPSMITH LONDON DRY",
  "HENDRICK’S",
  "MARSHALL LONDON DRY",
  "BOMBAY SAPPHIRE",
  "BOLS GENEVER BARREL AGED",
  "GIN MARE",
  "BEEFEATER PINK",
  "GREY SHINE",
  "TSELOVALNIK",
  "GREY GOOSE",
  "CHISTYE ROSY ORGANIC",
  "KOSKENKORVA",
  "REYKA",
  "LIMONCELLO PALLINI",
  "TSELOVALNIK COFFEE ELIXIR",
  "NIXTA",
  "SUZE",
  "LE BIRLOU",
  "CAMPARI",
  "APEROL",
  "SARTI",
  "AMARO MONTENEGRO",
  "CYNAR",
  "FERNET BRANCA",
  "ВЕРМУТ MARTINI ROSSO, FIERO, EXTRA DRY",
  "ВЕРМУТ MARTINI RISERVA AMBRATO, RUBINO",
  "ВЕРМУТ NORDÈS ROJO",
  "ВЕРМУТ DOLIN DRY",
  "ХЕРЕС LUSTAU PEDRO XIMÉNEZ",
  "ХЕРЕС TIO PEPE PALOMINO FINO",
  "ПОРТВЕЙН CALEM FINE RUBY",
  "ASAHI SUPER DRY",
  "GUINNESS DRAUGHT",
  "CORONA EXTRA",
  "CORONA CERO 0.0",
  "COCA-COLA",
  "ТОНИК",
  "ФИЛЬТР КОФЕ",
  "ВОДА PREALPI",
  "СОКИ ZUEGG",
  "Б/А ИГРИСТОЕ",
  "KRONE «BOREALIS» VINTAGE CUVEE BRUT",
  "MARTINI BRUT",
  "MARTINI PROSECCO ROSÉ",
  "PAUL G. VALENTIN CRÉMANT DE LIMOUX №88",
  "PATRICK PLUZE «FRENCH BUBBLE» ROSÉ",
  "HENRI GIRAUD ESPRIT NATURE",
  "RUHLMANN DIRINGER BRUT NATURE CRÉMANT D’ALSACE",
  "DIEL RIESLING RESERVE SEKT EXTRA BRUT",
  "RUINART BLANC DE BLANCS",
  "DOM PÉRIGNON",
  "ANSELMO MENDES «3 RIOS» ESCOLHA, VINHO VERDE",
  "DOMAINE LOUIS MOREAU, CHABLIS",
  "KARTHÄUSERHOF «BRUNO» RIESLING",
  "LOIMER, GRÜNER VELTLINER",
  "GERARD RAPET ALIGOTÉ",
  "CANTINE LUNAE VERMENTINO «ETICHETTA NERA»",
  "XAVIER MONNOT, MEURSAULT «LES CHEVALIERES»",
  "VRIESENHOF, CABERNET SAUVIGNON",
  "LA MAGIA IL VISPO",
  "TUPINIER-BAUTISTA, BOURGOGNE PINOT NOIR",
  "MEYER-NAKEL SPÄTBURGUNDER",
  "LE MASSÉ, CHIANTI CLASSICO",
  "«VINA BOSCONIA» RESERVA",
  "CHATEAU DU TUTRE, BORDEAUX",
  "DOMAINE NICOLAS BURGUEV, GEVREY-CHAMBERTIN «LES CRAIS»",
  "SANFELETTO, GREZZONE, COL FONDO",
  "CATCH 22 x OLEG ANDREEV · CIDER, LIMITED EDITION",
  "ORSI VIGNETO SAN VITO «SUI LIEVITI» PET NAT",
  "FRANCK PASCAL «RELIANCE» BRUT NATURE",
  "WEINHOF HAIDER «DELIBIOUS»",
  "ARCHIL · ЦИСКА",
  "SONS OF WINE «VIN DE MESS»",
  "CLEMENT LAVALLÉE «LES COPAINS D’ABORD» SAUVIGNON BLANC",
  "PARADISE GARAGE, PINOT NOIR №1",
  "JOHANNES ZILLINGER «PARCELLAIRE» ROUGE №1",
  "LUCIEN & FANNY ROCAULT, COTEAUX BOURGUIGNONS, GAMAY",
  "DOMAINE BALLORIN & F., SYRAH",
  "DOMAINE DIDON, PINOT NOIR",
];
